### ISSUE TITLE
YT Music AD bug

### ISSUE THREAD

**Issue by Blu-byte** [NoName-exe/revanced-extended#1]
So I just installed the latest apk from your github and now ads play whenever I play a new song. I've force stop it. Cleared all the data and even reinstalled it but it still persist please fix this.

**Comment by NoName-exe** [comment]
Yeah the music ads patch doesn't seem to want to apply. I'll get back to you when it's fixed. Meanwhile you can use [this](https://github.com/NoName-exe/revanced/releases/latest)

**Comment by NoName-exe** [comment]
Fixed in the latest release.
