### ISSUE TITLE
Magsik Version, YouTube does not install

### ISSUE THREAD

**Issue by soulspark666** [NoName-exe/revanced-extended#2]
Trying to install
youtube-revanced-magisk-v17.45.36-all.zip
But I cannot see it as an installed App on my device.

I tried to install the apk inside the zip but installing zip after that shows error that youtube is already installed for user 0.

**Comment by NoName-exe** [comment]
Did you reboot?

**Comment by soulspark666** [comment]
Yep, twice just in case.

**Comment by NoName-exe** [comment]
Woah that's wired. Turn off and remove the module and reboot twice. Then install it to see if it works.

**Comment by soulspark666** [comment]
Btw i tried to install j-hc release and it install without any issues? Is there a way i can share logs or something like that to find the issue?

**Comment by NoName-exe** [comment]
I'm too lazy to fix it 🥲.

**Comment by NoName-exe** [comment]
Also if you want to use revanced extended instead of normal revanced, you can go [here](https://t.me/rvx_lite) (installs yt as a user app).

**Comment by soulspark666** [comment]
Btw, fixed it, just replaced the modded apk from j-hc release with yours, and flashed that zip, so there is probably something wrong with the install script, hope this helps.

**Comment by NoName-exe** [comment]
> Btw, fixed it, just replaced the modded apk from j-hc release with yours, and flashed that zip, so there is probably something wrong with the install script, hope this helps.

Unfortunately I couldn't replicate anything but yeah there's either something wrong with the installer or the system partition in your device. I'll definitely take a look if there's more instances of this issue popping up.
